LangCorrect/server

langcorrect/posts/models.py
langcorrect/posts/utils.py
requirements/base.txt

closes #105
This PR centralizes the sentence-splitting logic by implementing it into a model signal. This avoids redundancy in the create/update views and ensures a more maintainable codebase. PostRows are no longer hidden if the original sentence in the post is changed or edited.
Benefits:
- PostRow instances will automatically be created when the post fixture is installed. This ensures that the PostRow objects are always in sync with the Post objects.
- Previously, each view had to correctly execute a helper function to split sentences. Moving this logic to a model signal eliminates this dependency, making the codebase easier to maintain.

105 ensure posts are being split

---

langcorrect/corrections/views.py
langcorrect/posts/templatetags/post_tags.py
langcorrect/templates/footer.html
langcorrect/templates/posts/partials/post_card.html
langcorrect/templates/posts/post_detail.html

- Sets `is_corrected` to True on post correction (fixes #110)
- Disables truncation in `render_post_card` (fixes #109)
- Removes misleading site language subtitle (fixes #108)

Various fixes

---

config/settings/base.py
locale/ar/LC_MESSAGES/django.po
locale/cs/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/django.po
locale/en_US/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fi/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
locale/he/LC_MESSAGES/django.po
locale/hr/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/django.po
locale/ja/LC_MESSAGES/django.po
locale/ko/LC_MESSAGES/django.po
locale/pl/LC_MESSAGES/django.po
locale/pt_BR/LC_MESSAGES/django.po
locale/ru/LC_MESSAGES/django.po
locale/tr/LC_MESSAGES/django.po
locale/zh_HAns/LC_MESSAGES/django.po
locale/zh_HAnt/LC_MESSAGES/django.po

closes #38
This PR updates the translation files in several ways:
- Migrates translations from locales that have more than 80% of their strings translated
- Uses ChatGPT to complete translations in locales with less than 80% translation coverage, or for any newly added strings
- Disables the `he` and `ar` language options due to text selection issues during the translation process (option will remain disabled until the majority of the strings are translated by a native speaker)
- Enables Rosetta to display where each string occurs in the codebase

38 migrate translations

---

locale/fr/LC_MESSAGES/django.po

PR to solve issue #131 
I found multiple translations that weren't formatted exactly as the English translations:
```diff
#: langcorrect/templates/contributions/contribution_list.html:11
#, python-format
msgid ""
"\n"
"          *Updates every %(hours)s hours\n"
"        "
msgstr ""
"\n"
-"*Mise à jour toutes les %(hours)s heures"
+"          *Mise à jour toutes les %(hours)s heures\n"
+" 
```
I made the change every time but I don't kow if that's necessary.
I also uncapitalized some translations that are preceded by a username (e.g. « john Vous a suivi. » vs « john vous a suivi »).
A relatively big change I did was also to replace the translation of "(Writing) Prompt" from « Incitation » to « Sujet de rédaction ». « Incitation » comes from the verb « inciter » which means to urge someone …

Verify French translations and add missing sentences (Solves #131)

---

langcorrect/templates/contributions/partials/contribution.html

It seems like `contribution.p`<kbd>Tab</kbd> auto-completed to the wrong variable.

Show `contribution.prompt_count` in "Total Prompts" instead of `contribution.post_count`

---

langcorrect/templates/base.html
langcorrect/templates/modals/notifications.html

closes #196 
The user object was previously overwritten, displaying the profile user's notifications instead of the logged-in user's.

Show only logged-in user's notifications

---

langcorrect/posts/views.py

closes #203 
This is ready for review @danielzeljko 
One question: is there any reason why you encoded `is_corrected` with 0 and 1 instead of using a Boolean field?

Show only corrected posts on learn page

---

langcorrect/languages/tests.py
langcorrect/languages/tests/factories.py
langcorrect/posts/tests/factories.py
langcorrect/posts/tests/test_views.py

This PR adds a couple of tests for PostListView.
Changes:
- Added qs tests for anonymous and authenticated users
- Added redirect tests when accessing `learn` and `following` mode for anonymous and authenticated users
- Added qs tests for filtering by language
Results:
All new tests pass, raising the coverage to 75%.

Add Tests for PostListView

---

config/urls.py

SEO rankings tanked a bit because all of our previously indexed posts were 404ing. This PR fixes this issue by informing search engines that the resource has been permanently moved to a new end point.

Add 301 redirects from /journal to /journals

---

langcorrect/posts/utils.py

closes #249 
This PR fixes an issue where traditional and simplified variants were not correctly processed and split due to a mismatch in language codes.

Fix chinese sentences not splitting correctly (#249)

---

langcorrect/corrections/views.py
langcorrect/templates/corrections/make_corrections.html
langcorrect/templates/modals/native_text.html

closes #246 
This PR introduces a stickied header where the user can view basic information about the user (gender of narration and language level) and includes a button when clicked would display an overview of the post including the original and native (conditionally rendered) texts.

Show post overview when making corrections (#246)

---

langcorrect/users/forms.py

closes #247 
I did not create a management command to strip the email portions from the username as it was not worth the time. Instead, I just changed it manually via the admin dashboard. I also notified all affected parties of the username change and informed them that they need to log in without using the email portion of their previous username.

Allow only alphanumeric and _ in usernames (#247)

---

langcorrect/corrections/views.py
langcorrect/follows/views.py
langcorrect/posts/api/views.py
langcorrect/posts/models.py

closes #191 
For all of these notification types, we should add translation. I considered it another task. This will fix the current bug and if we correct the translation files it will be fine.

Fix translation bug in notifications (#191)

---

langcorrect/templates/corrections/make_corrections.html

Reverts LangCorrect/server#300
Reverting because the modal button became unclickable.

Revert "Fix popup menu overlap (#298)"

---

langcorrect/prompts/templatetags/prompt_tags.py
langcorrect/prompts/urls.py
langcorrect/prompts/views.py
langcorrect/templates/prompts/partials/prompt_card.html
langcorrect/templates/prompts/prompt_list.html

closes #141 
closes #326
Adds a utility to convert prompts to journal entries and includes a static banner informing users that prompts should not be used to create journal entries.

141 convert prompt to journal

---

langcorrect/templates/contributions/partials/contribution.html
langcorrect/templates/emails/new_correction.html
langcorrect/templates/follows/follower_list.html
langcorrect/templates/follows/following_list.html
langcorrect/templates/navbar.html
langcorrect/templates/pages/checkout_canceled.html
langcorrect/templates/pages/checkout_success.html
langcorrect/templates/users/user_form.html
langcorrect/utils/mailing.py

closes #308
All relevant UI data points have been changed to use `display_name`.
A subsequent PR should correct the `display_name` function to use first/last name - or allow the user to modify `nickname`.

Use display_name instead of username

---

langcorrect/prompts/views.py
langcorrect/templates/no_content_card.html
langcorrect/templates/prompts/prompt_list.html

closes #358 
I've also created a card that we can hopefully reuse in other places where there's no content, in place of the empty table we're showing now.
To pass in a reversed url into Django's `include`, the best solution that I was able to find was to assign the link to a variable. Please lmk if there's a better way to handle this!

358 Don't show a completed prompt if the response has been removed 

---

langcorrect/posts/views.py

fixes #391 
Temp fix. We should use choices from LevelChoices instead of assigning the level directly.

Fix language level assignment in PostCreateView (#391)

---

langcorrect/templates/users/user_detail.html
langcorrect/users/views.py

Orders user profile languages by -level (#357)

---

langcorrect/templates/posts/partials/post_card.html

fixes #414 
Adds tags to posts as badges.
Appears at the bottom of text.
Not clickable yet, but since there is no existing tag search functionality, probably better in a separate PR

Adds badge for post tag to post_card (#414)

---

langcorrect/templates/navbar.html

There is a current ongoing production issue (#401) where ghost notification counts are sporadically displayed. To address this problem, this PR implements a temp fix that retrieves the unread notification count without relying on the cache. By doing so, we can investigate whether the issue is connected to the caching mechanism.

Bypass cache when querying for notification count (#401)

---

langcorrect/corrections/views.py
langcorrect/templates/corrections/make_corrections.html

fixes #468 
This PR adds an indicator for post title and shows a friendly tool-tip to remind users to correct the title accordingly

Show indicator for post title (#468)

---

config/urls.py
langcorrect/prompts/api/serializers.py
langcorrect/prompts/api/urls.py
langcorrect/prompts/api/views.py
langcorrect/users/api/views.py

fixes #145 
```
path(
"<str:slug>/",
view=PromptRetrieveUpdateDestroyAPIView.as_view(),
name="prompt-detail",
),
```
I wasn't able to figure out a way to remove the trailing slash requirement without adding this path to the router or disabling it in settings completely. So for now, a trailing slash will be required until the full switch to an API backend is complete.

145 prompts api

---

langcorrect/contributions/models.py
langcorrect/managers.py
langcorrect/posts/models.py
langcorrect/templates/posts/partials/card_badges.html
langcorrect/templates/posts/partials/card_header.html
langcorrect/users/models.py

This PR excludes inactive users from various querysets to ensure they are not shown where active user data is expected.
In some cases (e.g., displaying corrections on a post), inactive users are not excluded; instead, their user information is replaced with a cute default avatar and name.

feat: exclude inactive users from qs
