LangCorrect/server

- langcorrect/contributions/models.py
- langcorrect/templates/navbar.html
- langcorrect/users/models.py
- Adds a link to the Rankings page under the community dropdown in navbar (closes #116)
- Adds a signal to create a contribution record when a new user is registered (closes #115)
> Various fixes

- langcorrect/corrections/helpers.py
- langcorrect/corrections/templatetags/correction_tags.py
- langcorrect/posts/views.py
- langcorrect/templates/corrections/partials/popular_corrector.html
- langcorrect/templates/corrections/popular_correctors.html
- langcorrect/templates/posts/post_list.html
- langcorrect/users/models.py
closes #117 
This PR implements the "Popular Correctors" widget.
> Add popular correctors widget (#117)

- config/settings/base.py
- config/settings/production.py
- requirements/production.txt
This PR addresses two primary issues:
- Resolves an issue where static assets were not being loaded correctly in our newly created server. Specifically, it modified the `STATIC_ROOT` to align with Nginx's `root` directive, making it easier to serve static files.
- Disables the collectfast package as it is no longer maintained.
> Update production settings

- langcorrect/users/management/commands/verify_emails.py
closes #12 
Please let me know if you have any comments @danielzeljko
> Verify emails automatically (#12)

- langcorrect/templates/navbar.html
closes #163 
I think that's it
> Fix logout icon (#163)

- config/urls.py
- langcorrect/templates/pages/community_guidelines.html
> Add community guidelines page (#168)

- config/urls.py
- langcorrect/templates/footer.html
- langcorrect/templates/pages/privacy_policy.html
closes #166
This PR adds a privacy policy page and updates the community guidelines link in the footer.
> 166 privacy policy page

- config/urls.py
- langcorrect/templates/footer.html
- langcorrect/templates/pages/terms_of_service.html
> Add terms of service page (#167)

- langcorrect/templates/pagination.html
> Fix pagination template to show previous page number

- langcorrect/templates/navbar.html
> Forums removed

- langcorrect/users/forms.py
> Fix UserSignupForm save() to handle existing accounts (#206)

- langcorrect/prompts/views.py
- langcorrect/templates/navbar.html
> Fix prompt link not active when selected (#204)

- langcorrect/static/css/project.css
- langcorrect/static/css/project.min.css
- langcorrect/static/sass/custom_bootstrap_vars.scss
- langcorrect/templates/pages/home.html
> 225 update primary color code

- langcorrect/templates/posts/post_list.html
> Show CTA instead of language filter for anon (#224)

- .github/workflows/ci.yml
- langcorrect/posts/models.py
> Fix sentences not splitting correctly (#202)

- langcorrect/templates/posts/post_detail.html
> Fix content overflow in chrome (#237)

- langcorrect/posts/views.py
> Fix post language level not being set (#254)

- langcorrect/corrections/views.py
- langcorrect/follows/views.py
- langcorrect/posts/api/views.py
- langcorrect/posts/models.py
- locale/ar/LC_MESSAGES/django.po
- locale/cs/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/en_US/LC_MESSAGES/django.po
- locale/es/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- locale/he/LC_MESSAGES/django.po
- locale/hr/LC_MESSAGES/django.po
- locale/it/LC_MESSAGES/django.po
- locale/ja/LC_MESSAGES/django.po
- locale/ko/LC_MESSAGES/django.po
- locale/pl/LC_MESSAGES/django.po
- locale/pt_BR/LC_MESSAGES/django.po
- locale/ru/LC_MESSAGES/django.po
- locale/tr/LC_MESSAGES/django.po
- locale/zh_HAns/LC_MESSAGES/django.po
- locale/zh_HAnt/LC_MESSAGES/django.po
closes #191 
Really nice find with `gettext_noop`! Everything seems to be working correctly now @itshesam.
> 191 bugfix translation

- langcorrect/subscriptions/views.py
Fixed an issue with possible information exposure through an exception.
> Use generic msg for client checkout error

- langcorrect/languages/views.py
Fixes sentry error: LANGCORRECT-14
> Fix anon user error in LanguageLevelDeleteView (#273)

- langcorrect/posts/tests/test_views.py
- langcorrect/posts/views.py
> Sort language by recent & uncorrected (#268)

- langcorrect/templates/admin/users/change_list.html
- langcorrect/users/admin.py
closes #278 
Added a chart that displays the number of registrations each day; Updated the list_display to include languages and active status. I did not worry about responsiveness because the admin base template will eventually be changed.
> Add chartjs and update list_display to UserAdmin (#278)

- .github/workflows/ci.yml
- README.md
> Download Fugashi dictionaries when running tests in ci (#269)

- langcorrect/templates/corrections/partials/correction.html
- langcorrect/templates/corrections/partials/user_correction_card.html
closes #205 
- I decided to make the text color for perfect sentences black (primary) because I thought it's easier to look at on green background.
- One thing I'm unsure about is the muted text for extra comments. I think it looks fine for short comments, but a bit hard to follow for longer ones. Let me know what you think @danielzeljko
> Add background colors to corrections

- langcorrect/posts/views.py
> Hide own posts from learn mode (#282)

- langcorrect/templates/corrections/make_corrections.html
> Fix popup menu overlap (#298)

- langcorrect/static/css/project.css
- langcorrect/static/css/project.min.css
- langcorrect/static/sass/project.scss
- langcorrect/templates/corrections/make_corrections.html
- langcorrect/templates/corrections/partials/correction.html
- langcorrect/templates/modals/native_text.html
- langcorrect/templates/posts/partials/post_card.html
closes #310 
This PR installs Chinese fonts and dynamically sets the font-family based on the `lang` attribute.  This attribute was added to posts, corrections, make correction page and it's respective text overview modal.
> 310 noto sans chinese fonts

- langcorrect/static/css/project.css
- langcorrect/static/css/project.min.css
- langcorrect/static/sass/project.scss
- langcorrect/templates/posts/partials/post_card.html
Fixes two small issues where the post title was not bolded and the incorrect font being used
> Fix bold in titles

- langcorrect/templates/navbar.html
closes #325 
Besides the changes mentioned in #325, I've also changed the color of the Write button. I believe that it creates a better visual cue whether or not there are notifications. Pls let me know what you think @danielzeljko
> 325 update navbar

- langcorrect/posts/api/views.py
- langcorrect/static/js/post_detail.js
- langcorrect/static/js/project.js
- langcorrect/static/js/project.min.js
- langcorrect/static/js/service.js
- langcorrect/templates/base.html
- langcorrect/templates/corrections/partials/correction.html
- langcorrect/templates/corrections/partials/user_correction_card.html
- langcorrect/templates/posts/post_detail.html
closes #157
This PR moves the reply form to be below the reply section, and displays a toast notification for errors.
https://github.com/LangCorrect/server/assets/115326106/d67161b5-2084-4816-a368-83fd5719fa5d
> 157 improve UI for replies

- langcorrect/posts/helpers.py
- langcorrect/posts/models.py
- langcorrect/posts/tests/test_views.py
- langcorrect/posts/views.py
closes #346 
This PR hides older sentences that have been edited and no longer found in the text.
https://github.com/LangCorrect/server/assets/115326106/b599e902-2827-4772-807a-f48bf94d017d
> Hide old post rows when post is edited (#346)

- langcorrect/templates/navbar.html
- locale/ar/LC_MESSAGES/django.po
- locale/cs/LC_MESSAGES/django.po
- locale/de/LC_MESSAGES/django.po
- locale/en_US/LC_MESSAGES/django.po
- locale/es/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- locale/he/LC_MESSAGES/django.po
- locale/hr/LC_MESSAGES/django.po
- locale/it/LC_MESSAGES/django.po
- locale/ja/LC_MESSAGES/django.po
- locale/ko/LC_MESSAGES/django.po
- locale/pl/LC_MESSAGES/django.po
- locale/pt_BR/LC_MESSAGES/django.po
- locale/ru/LC_MESSAGES/django.po
- locale/tr/LC_MESSAGES/django.po
- locale/zh_HAns/LC_MESSAGES/django.po
- locale/zh_HAnt/LC_MESSAGES/django.po
> 348 add trans tag to write button mobile

- langcorrect/posts/helpers.py
- langcorrect/posts/models.py
- langcorrect/posts/tests/test_views.py
- langcorrect/posts/views.py
It seems this PR introduced a bug where duplicate post rows were being created, despite the testcases for counting the number of rows created passing.
> Revert #346 Hide Old PostRows

- langcorrect/posts/helpers.py
- langcorrect/posts/models.py
- langcorrect/posts/views.py
fixes #346 
https://github.com/LangCorrect/server/assets/115326106/b599e902-2827-4772-807a-f48bf94d017d
> 346 hide old post rows

- langcorrect/posts/models.py
New `PostRow` instances were created for each sentence without checking if equivalent rows already existed.
> Fix duplicate PostRow issue when corrections are made

- langcorrect/prompts/views.py
> Fix PromptCreateView not inheriting LoginRequiredMixin (#374)

- langcorrect/corrections/utils.py
> Add base_url to weasyprint HTML method

- langcorrect/subscriptions/views.py
> Add login required to create_checkout_session (#380)

- langcorrect/corrections/management/commands/update_is_correct.py
- langcorrect/corrections/tests.py
- langcorrect/corrections/tests/test_views.py
- langcorrect/corrections/views.py
- langcorrect/languages/tests/factories.py
@danielzeljko 
closes #26 
I added ```seed.sql``` as fixtures to make it easier to write tests.
Also added ```vscode``` directory to gitignore, it was annoying for me :D
If number of correctors get 0 then the ```is_corrected``` field should be 0, right ?
And added the management command as you said, but i don't know how much load is on the database and don't have any estimation of the number of posts that need to be updated, so i just wrote the simplest possible way.
There's something problem in japanese splitting, it makes the pipline fail, i didn't find how to fix it, maybe you encountered it before.
> [WIP] 26 update is corrected field

- config/settings/base.py
changed it so it redirects you to feed after login i couldn't test but its seems like it would work just fine if i did :) feel free to edit or ask me to do it if anything is wrong :) 
Issue: [#356](https://github.com/LangCorrect/server/issues/356)
@keyxcode if you have time feel free to test it
> redirecting to feed after login

- langcorrect/templates/posts/post_list.html
> Show server time in the sidebar (#280)

- langcorrect/templates/users/user_detail.html
fixes #418 
Adds a link to the password change form in the sidebar of the user page
> Add a link to change password (#418)

- langcorrect/templates/navbar.html
> 411 Rename nav buttons

- langcorrect/posts/forms.py
- langcorrect/prompts/views.py
- langcorrect/templates/prompts/convert_prompt.html
- langcorrect/templates/prompts/prompt_detail.html
Show the post form before converting a prompt to a post. This way we can manually select the language and make any changes as needed.
> Show form before converting prompt to a post

- langcorrect/templates/base.html
> Add google adsense meta code

- langcorrect/static/js/post_list.js
> Fix languageSelect is null (#465)

- config/urls.py
- langcorrect/templates/ads.txt
- langcorrect/templates/robots.txt
Adds a robots.txt and ads,txt endpoint
> Add ads.txt and robots.txt

- langcorrect/templates/robots.txt
Disallowed semrush crawlers as it was making too many requests to the site in a short period of time
> Block semrush crawler

- config/api/pagination.py
- config/api/permissions.py
- config/api_router.py
- config/settings/base.py
- langcorrect/languages/serializers.py
- langcorrect/posts/api/serializers.py
- langcorrect/posts/api/views.py
- langcorrect/posts/forms.py
- langcorrect/posts/tests/factories.py
- langcorrect/posts/tests/test_drf_urls.py
- langcorrect/posts/tests/test_drf_views.py
- langcorrect/posts/validators.py
- langcorrect/users/api/serializers.py
- langcorrect/users/tests/test_drf_urls.py
- langcorrect/users/tests/test_drf_views.py
> 144 posts api

- langcorrect/prompts/api/serializers.py
- langcorrect/prompts/api/urls.py
- langcorrect/prompts/api/views.py
- langcorrect/prompts/tests/test_drf_views.py
> 145 prompts api

- langcorrect/prompts/tests.py
Fix failing ci test due to wrong test file being collected
> Remove unused test file

- config/api/authentication.py
- config/settings/base.py
- config/settings/views.py
- config/urls.py
- requirements/base.txt
Adds token based authentication with http only cookies support
> Add token-based authentication with cookies support

- config/settings/base.py
- config/settings/local.py
- config/settings/production.py
- requirements/base.txt
> Remove whitenoise middleware and storage (#537)

- config/settings/production.py
Temp fix to resolve `Missing staticfiles manifest`
> Update staticfiles storage backend to hotfix Missing staticfiles manifest

- langcorrect/posts/api/serializers.py
> chore: Update minimum message length validation in PostReplySerializer

- langcorrect/posts/helpers.py
- langcorrect/posts/tests/test_views.py
- langcorrect/posts/urls.py
- langcorrect/posts/views.py
- langcorrect/templates/posts/post_restricted.html
- langcorrect/users/models.py
Thanks to Monsieur_Éléphant, Brylarke, and baguette for all of the suggestions and feedback 🎉
> 568 ratio calc adjustments

- langcorrect/templates/notifications/partials/notification.html
> refactor(notification): use display name when rendering notifications

- .github/workflows/ci.yml
- langcorrect/contributions/helpers.py
- langcorrect/contributions/tasks.py
- langcorrect/users/helpers.py
> refactor(rankings): optimize algo to avoid hitting soft time limits

- langcorrect/follows/views.py
- langcorrect/languages/views.py
SoftDeletableModel was removed
> fix: remove soft=False from delete() calls to resolve TypeError
